### ISSUE TITLE
Trigger only on shell exit

### ISSUE THREAD

**Issue by jdahm** [meaningful-ooo/sponge#1]
This may not be possible, but is there a way to trigger sponging for the commands run only after the shell is exited? I really like this feature, but I find myself scrolling back for commands that failed as I'm developing scripts, etc. Thanks for the great work!

**Comment by andreiborisov** [comment]
Brilliant suggestion, thank you!

It's possible, I'll add this in the next release👌🏻

**Comment by andreiborisov** [comment]
<p><a href="https://linear.app/meaningful/issue/HAW-10/option-to-delete-only-on-exit">HAW-10 Option to delete only on exit</a></p>

**Comment by andreiborisov** [comment]
Done: https://github.com/meaningful-ooo/sponge#-purge-only-on-exit

@jdahm please, let me know if you'll have any issues!
